[package]
name = "quarrel-indexer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
quarrel-core = { workspace = true }
quarrel-chain = { workspace = true }
quarrel-store = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
